name: compilation
"on":
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: site
        run: npm ci
      - name: Build Foundation 6
        working-directory: site
        run: npm run build
